apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-29T13:08:55Z"
  labels:
    app: redis-master
  name: redis-master
  namespace: default
  resourceVersion: "41328"
  selfLink: /api/v1/namespaces/default/services/redis-master
  uid: 65d79a59-12a9-11ea-a577-42010a8402b2
spec:
  clusterIP: 10.77.9.71
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30315
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-master
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.205.104.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-11-29T12:59:11Z"
  generation: 4
  labels:
    app: redis-master
  name: redis-master
  namespace: default
  resourceVersion: "42149"
  selfLink: /apis/apps/v1/namespaces/default/deployments/redis-master
  uid: 09afebdb-12a8-11ea-a577-42010a8402b2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-master
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-master
    spec:
      containers:
      - image: eu.gcr.io/prjpolytech/redis
        imagePullPolicy: Always
        name: redis-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-29T12:59:11Z"
    lastUpdateTime: "2019-11-29T12:59:13Z"
    message: ReplicaSet "redis-master-66c64c4445" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-11-29T13:13:40Z"
    lastUpdateTime: "2019-11-29T13:13:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1