apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-master
  name: redis-master
  namespace: default
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-master
    tier: backend
    role: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-master
  name: redis-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-master
    spec:
      containers:
      - image: eu.gcr.io/prjpolytech/redis
        imagePullPolicy: IfNotPresent
        name: redis-sha256
      restartPolicy: "Always"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: retwis
  name: retwis
  namespace: default
spec:
  ports:
  - nodePort: 32332
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: retwis
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: retwis
  name: retwis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retwis
  template:
    metadata:
      labels:
        app: retwis
    spec:
      containers:
      - image: RETWIS_DOCKER_IMAGE
        imagePullPolicy: "Always"
        name: retwis-sha256
      restartPolicy: Always

