apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-master
  name: redis-master
spec:
  ports:
  - nodePort: 30315
    port: 6379
    targetPort: 6379
  selector:
    app: redis-master
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-master
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - image: eu.grc.io/prjpolytech/redis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: retwis
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: retwis
  name: retwis
spec:
  replicas: 1
    spec:
      containers:
      - image: RETWIS_DOCKER_IMAGE
        imagePullPolicy: Always
      restartPolicy: Always